### ISSUE TITLE
compsgui wishlist

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/eegDb#53]
#### OVERVIEW

`pop_selectcomps_new` was written with compatibility with `pop_selectcomps` in mind.
These restrictions turned out to be too limiting so the new version = `compsgui` works a little different and has a short and easy to type name.
You can use it without `db` this way: `compsgui(EEG)`

This issue tracks ideas and considerations about how the function should work and how it could be enhanced.
#### SPECIFIC TASKS
- [ ] tagging components
- [ ] left and right arrows work as left and right gui buttons
- [ ] explore impact of component removal on signal with (some) other components removed
- [x] do not save topos in the database
- [x] right-click - change status
- [x] position in the centre of the screen
- [ ] size options
- [ ] add page info
- [x] change visual state only if not the same as in info (in sync)
- [ ] change status colors to those from screenshot
- [ ] grid options (to specify the dimensions of the topo grid)
#### LATER:

I will think about adding things like:
- [x] change names to `compsgui`
- [x] recover EEG with all the components even if some were marked
- [ ] options for compo plotting
- [ ] getting plotting options from eegDb gui (other GUI)
- [ ] check for figure existence
- [ ] if one resizes the figure the buttons do should not get scaled so much - some limits should be set
- [ ] buttons are sometimes white - gray button backgroundcolor (taken from info) instead of white
#### CONSIDERATIONS

:question: maybe allow plotting maps without EEG data (maybe ...)

**Comment by mzakrzewska** [comment]
Not sure at which stage EEG is recovered when getting to pop_selectcomps_new by ctr-e, but it should do the 'ICAnorem' recover by default - as it is now, you can't inspect (or un-reject) previously rejected components.

**Comment by mmagnuski** [comment]
True, this will have to be changed but along with #28.
The idea is that the recovered file should be recovered without rejections - only filtered and epoched.
Removing epochs and components is fast so it can be performed on the fly - and would reduce wait time if component rejections or epoch rejections are changed (no need to filter again).
Currently you cannot inspect components rejected previously, but you do not have to recover again. If you press 'c' in the main window (multiple topoplots) to compare changes with all rejected components - you get a warning that some are already rejected. See `szoppracz` for this.

**Comment by mmagnuski** [comment]
For link between `winreject` and this function look for `linkfun_` + thisfunctionname
