### ISSUE TITLE
in function: plot - problem with using 'number of channels to display' - crash when I used arrows to scroll

### ISSUE THREAD

**Issue by akolodziej** [mmagnuski/eegDb#59]

**Comment by mmagnuski** [comment]
It is worth checking whether this problem persists in the current eeglab version and reporting to eeglab developers if it does.
We are moving away from `eegplot` (everything will use `fastplot`) so this bug will not be dealt here.

**Comment by mmagnuski** [comment]
Closing as not eegDb bug
